### PR TITLE
Complete rewrite of generate_site_positions.py

### PR DESCRIPTION
**Pull request by ecsedi**
This is a complete rewrite of generate_site_positions.py.
The new version runs under python3 as well as python2.
It runs 30% faster than the previous version.
It corrects an error found in the previous version where the very last number in the result was wrong (it was one too many).
It can work with multiple test strings at the same time.
The script contains a dictionary for genome/filename mappings and another one for enzyme/test string mappings which users can modify easily according to their own purposes.

### CODE REVIEW

**Comment by Zanecrc1** [comment]
Some RE that are currently being worked with to push removal of fragmentation via sonication have variable sites where n nucleotide in the string can be either A or T (notated as W) , G or A (notated as R) etc. 

It may be useful to allow for test strings based on these variable sites.

A full list would be:

N	A, C, G or T
M	A or C
R	A or G
W	A or T
Y	C or T
S	C or G
K	G or T
H	A, C or T
B	C, G or T
V	A, C or G
D	A, G or T

**Comment by ecsedi** [comment]
OK, I created a new pull request (I hope it's OK, I'm quite new to github) which contains the requested wildcard matches.

**Comment by Zanecrc1** [comment]
Amazing.

**Comment by ecsedi** [comment]
I didn't like that big performance penalty introduced by using regular expressions, so I created a third version of the program. Now it can separate the different cases and uses regular expression matches only when it is needed, otherwise it works with the much faster string prefix method. This time I'm satisfied with the results. I'm going to upload it as soon as I finish the tests.

**Comment by ecsedi** [comment]
I'm closing this pull request in favor of my latest version of the script.

**Pull request closed without merging**
